<div class="container">
	<div class="row">
		<h1>Contato</h1>
		<p>Preencha o formulário</p>
	</div>
	
	<div class="row">
		<div class="col-lg-12">
			<ul>
				<li>
					Entre em contato pelo nosso telefone 
					<a href="tel:+5554999999999">
						+55(54)99999-9999
					</a>
				</li>
				<li>
					Entre em contato pelo nosso email: 
					<a href="mailto:email@email.com">
						email@email.com
					</a>
				</li>
				<li>
					Entre em contato pelo nos enviando uma mensagem: 
					<a href="contato/mensagem">
						Preencha o formulário
					</a>
				</li>			
			
			</ul>					
		</div>
	</div>
	
</div>